# Generated by Django 3.2 on 2021-06-29 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
